sudo: required

services:
  - docker

env:
  - COMPOSE_VERSION=1.6.1

before_install:
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin

before_script:
 - git lfs pull

script:
  - docker-compose build
  - docker-compose up -d
  - docker-compose -f docker-compose.yml -f docker-compose.dev.yml run --rm --user='root' app coverage run manage.py test --verbosity=2

after_success:
  - docker-compose -f docker-compose.yml -f docker-compose.dev.yml run --rm --user='root' -e TRAVIS=$TRAVIS -e TRAVIS_JOB_ID=$TRAVIS_JOB_ID app coveralls
