version: '2'

services:
  app:
    build: .
    restart: always
    volumes:
      - 'torrent:/torrents'
      - 'static:/static'
      - 'upload:/uploads'
      - './src/:/app'
    environment:
      - SECRET_KEY
      - TZ
